import { ValidationRecord } from '../types/validation';

/**
 * 校验记录 ValidationRecords
 */
export const mockValidationRecords: Record<string, ValidationRecord> = {
  slot_01: {
    local_id: "slot_01",
    overall_status: "PASS",
    rule_checks: [
      {
        rule_id: "RULE_SCORE_SUM",
        category: "structure",
        name: "分值结构平衡性",
        status: "PASS",
        detail: "评分点之和等于题面分值 400 (4分)",
      },
      {
        rule_id: "RULE_SYMPY_MATH",
        category: "math_consistency",
        name: "SymPy 代数表达式严格检验",
        status: "PASS",
        detail: "求解 Δ=16-4k>0 结果为 k<4，与参考答案 opt_A 严格等价",
        evidence: "solve(16 - 4*k > 0, k) -> (-oo, 4)",
      },
      {
        rule_id: "RULE_SCOPE_BOUNDARY",
        category: "scope_adherence",
        name: "课程大纲与知识点边界",
        status: "PASS",
        detail: "命中已教范围：一元二次方程根的判别式，未检测到超纲内容",
      },
      {
        rule_id: "RULE_ANTI_LEAK",
        category: "anti_leakage",
        name: "盲解隔离与防泄露",
        status: "PASS",
        detail: "盲解请求上下文中无 private.answers 属性",
      },
    ],
    blind_solve: {
      solver_role: "blind-solver",
      model_id: "deepseek-chat",
      is_same_model: true,
      derived_answer: "A",
      selected_option_ids: ["opt_A"],
      steps: [
        { step_number: 1, description: "识别题目要求一元二次方程有两不相等实数根，确立条件 Δ > 0" },
        { step_number: 2, description: "代入 a=1, b=-4, c=k 得 Δ = 16 - 4k" },
        { step_number: 3, description: "解不等式 16 - 4k > 0 得到 k < 4" },
        { step_number: 4, description: "与选项比对，选项 A 吻合" },
      ],
      match_reference: true,
      notes: "盲解答案与命题作者参考答案完全一致。已标注 SAME_MODEL。",
      duration_ms: 1850,
    },
    verified_at: "2026-09-17T14:40:00Z",
    content_hash: "sha256:7f92a104b2c159841f...",
    repair_count: 0,
  },
  slot_02: {
    local_id: "slot_02",
    overall_status: "PASS",
    rule_checks: [
      {
        rule_id: "RULE_SCORE_SUM",
        category: "structure",
        name: "分值结构平衡性",
        status: "PASS",
        detail: "各评分步之和等于题面分值 400",
      },
      {
        rule_id: "RULE_SYMPY_MATH",
        category: "math_consistency",
        name: "几何相似比计算检验",
        status: "PASS",
        detail: "由 AD/DB=2/3 推得 AD/AB=2/5，(2/5)^2 = 4/25 吻合选项 C",
      },
      {
        rule_id: "RULE_SCOPE_BOUNDARY",
        category: "scope_adherence",
        name: "教学考查范围校验",
        status: "PASS",
        detail: "符合人教版九年级相似三角形面积定理要求",
      },
    ],
    blind_solve: {
      solver_role: "blind-solver",
      model_id: "deepseek-chat",
      is_same_model: true,
      derived_answer: "C",
      selected_option_ids: ["opt_C"],
      steps: [
        { step_number: 1, description: "由平行线分线段成比例推导 ADE ~ ABC" },
        { step_number: 2, description: "相似比为 AD/AB = 2/(2+3) = 2/5" },
        { step_number: 3, description: "面积比为相似比的平方 (2/5)^2 = 4/25" },
      ],
      match_reference: true,
      notes: "比对无偏差，选项 C 正确。",
      duration_ms: 1920,
    },
    verified_at: "2026-09-17T14:40:02Z",
    content_hash: "sha256:8b44c201a93821...",
    repair_count: 0,
  },
  slot_03: {
    local_id: "slot_03",
    overall_status: "REVIEW",
    rule_checks: [
      {
        rule_id: "RULE_SCORE_SUM",
        category: "structure",
        name: "分值结构平衡性",
        status: "PASS",
        detail: "总分 400，步骤分合计 400",
      },
      {
        rule_id: "RULE_SYMPY_MATH",
        category: "math_consistency",
        name: "SymPy 代数化简检验",
        status: "PASS",
        detail: "计算 x1^2 + x2^2 = 11，吻合选项 B",
      },
      {
        rule_id: "RULE_SCOPE_BOUNDARY",
        category: "scope_adherence",
        name: "教学考查范围提示",
        status: "REVIEW",
        detail: "部分教材省份将韦达定理列为选学/补充内容，需审核教师确认本校是否已教",
        evidence: "检测到关键词：韦达定理/根与系数关系",
      },
    ],
    blind_solve: {
      solver_role: "blind-solver",
      model_id: "deepseek-chat",
      is_same_model: true,
      derived_answer: "B",
      selected_option_ids: ["opt_B"],
      steps: [
        { step_number: 1, description: "根据韦达定理: x1+x2=3, x1*x2=-1" },
        { step_number: 2, description: "x1^2+x2^2=(x1+x2)^2-2*x1*x2=9-(-2)=11" },
      ],
      match_reference: true,
      notes: "计算一致，标记 REVIEW 提醒确认课程范围。",
      duration_ms: 1730,
    },
    verified_at: "2026-09-17T14:40:04Z",
    content_hash: "sha256:1a77490fe42...",
    repair_count: 0,
  },
  slot_08: {
    local_id: "slot_08",
    overall_status: "PASS",
    rule_checks: [
      {
        rule_id: "RULE_SCORE_SUM",
        category: "structure",
        name: "大题给分步完整性",
        status: "PASS",
        detail: "各步分值分别为 400, 400, 400, 600，合计 1800 (18分)",
      },
      {
        rule_id: "RULE_SYMPY_MATH",
        category: "math_consistency",
        name: "判别式与二次方程求解核对",
        status: "PASS",
        detail: "判别式恒为 1，第(2)问 m 的根为 2 和 -3，双向验证通过",
      },
      {
        rule_id: "RULE_SCOPE_BOUNDARY",
        category: "scope_adherence",
        name: "题型与能力要求契合度",
        status: "PASS",
        detail: "属于综合推演题，逻辑链条完备，未超纲",
      },
    ],
    blind_solve: {
      solver_role: "blind-solver",
      model_id: "deepseek-chat",
      is_same_model: true,
      derived_answer: "(1) Δ=1>0 证明成立; (2) m=2 或 m=-3",
      steps: [
        { step_number: 1, description: "展开 Δ = (2m+1)^2 - 4(m^2+m) = 1 > 0" },
        { step_number: 2, description: "列方程 (2m+1)^2 - 2(m^2+m) = 13" },
        { step_number: 3, description: "化简得 2m^2 + 2m - 12 = 0 => m=2 或 m=-3" },
      ],
      match_reference: true,
      notes: "解答题盲解推理过程严密，步骤给分点与参考标准一致。",
      duration_ms: 2450,
    },
    verified_at: "2026-09-17T14:40:08Z",
    content_hash: "sha256:49c0182fba89...",
    repair_count: 0,
  },
};
