import { BlueprintSlot } from '../types/spec';

/**
 * 初中数学蓝图槽位 (Blueprint Slots)
 */
export const mockMathSlots: BlueprintSlot[] = [
  {
    slot_id: "slot_01",
    order: 1,
    section_id: "sec_1",
    kind: "single_choice",
    target_topic: "一元二次方程判别式",
    cognitive_target: "理解与辨析",
    estimated_difficulty: "basic",
    score_x100: 400,
    answer_space_lines: 2,
    status: "READY",
  },
  {
    slot_id: "slot_02",
    order: 2,
    section_id: "sec_1",
    kind: "single_choice",
    target_topic: "相似三角形判定定理",
    cognitive_target: "几何推理",
    estimated_difficulty: "medium",
    score_x100: 400,
    answer_space_lines: 2,
    status: "READY",
  },
  {
    slot_id: "slot_03",
    order: 3,
    section_id: "sec_1",
    kind: "single_choice",
    target_topic: "韦达定理与根的符号",
    cognitive_target: "代数运算",
    estimated_difficulty: "medium",
    score_x100: 400,
    answer_space_lines: 2,
    status: "REVIEW_REQUIRED",
  },
  {
    slot_id: "slot_04",
    order: 4,
    section_id: "sec_1",
    kind: "single_choice",
    target_topic: "相似多边形性质",
    cognitive_target: "应用计算",
    estimated_difficulty: "advanced",
    score_x100: 400,
    answer_space_lines: 2,
    status: "READY",
  },
  {
    slot_id: "slot_05",
    order: 5,
    section_id: "sec_2",
    kind: "fill_blank",
    target_topic: "比例中项计算",
    cognitive_target: "基础计算",
    estimated_difficulty: "basic",
    score_x100: 400,
    answer_space_lines: 2,
    status: "READY",
  },
  {
    slot_id: "slot_06",
    order: 6,
    section_id: "sec_2",
    kind: "fill_blank",
    target_topic: "韦达定理代数式化简",
    cognitive_target: "运算求解",
    estimated_difficulty: "medium",
    score_x100: 400,
    answer_space_lines: 2,
    status: "READY",
  },
  {
    slot_id: "slot_07",
    order: 7,
    section_id: "sec_2",
    kind: "fill_blank",
    target_topic: "一元二次方程有实根条件",
    cognitive_target: "分类讨论",
    estimated_difficulty: "medium",
    score_x100: 400,
    answer_space_lines: 2,
    status: "READY",
  },
  {
    slot_id: "slot_08",
    order: 8,
    section_id: "sec_3",
    kind: "solution",
    target_topic: "方程综合求解与参数范围",
    cognitive_target: "综合推演",
    estimated_difficulty: "medium",
    score_x100: 1800,
    answer_space_lines: 8,
    status: "READY",
  },
  {
    slot_id: "slot_09",
    order: 9,
    section_id: "sec_3",
    kind: "solution",
    target_topic: "相似三角形证明与面积比",
    cognitive_target: "逻辑证明与几何综合",
    estimated_difficulty: "advanced",
    score_x100: 1800,
    answer_space_lines: 10,
    status: "READY",
  },
  {
    slot_id: "slot_10",
    order: 10,
    section_id: "sec_3",
    kind: "solution",
    target_topic: "一元二次方程实际应用题",
    cognitive_target: "数学建模与实际问题转化",
    estimated_difficulty: "medium",
    score_x100: 1800,
    answer_space_lines: 8,
    status: "READY",
  },
  {
    slot_id: "slot_11",
    order: 11,
    section_id: "sec_3",
    kind: "solution",
    target_topic: "动态几何与相似极值讨论",
    cognitive_target: "探究与反思",
    estimated_difficulty: "advanced",
    score_x100: 1800,
    answer_space_lines: 12,
    status: "REVIEW_REQUIRED",
  },
];
